FROM marselester/opencv2:latest
MAINTAINER Marsel Mavletkulov <marselester@ya.ru>

RUN wget -q -O install-deps https://raw.githubusercontent.com/torch/distro/master/install-deps && \
    echo 'APT::Get::Assume-Yes "true";' > /etc/apt/apt.conf.d/yes && \
    printf '#/bin/bash\n"$@"' > /usr/bin/sudo && \
    chmod +x /usr/bin/sudo && \
    bash install-deps

RUN git clone https://github.com/torch/distro.git ~/torch --recursive && \
    cd ~/torch && \
    ./install.sh && \
    ln -s /root/torch/install/bin/* /usr/local/bin

RUN apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN luarocks install nn && \
    luarocks install dpnn && \
    luarocks install image && \
    luarocks install optim && \
    luarocks install csvigo && \
    luarocks install torchx && \
    luarocks install tds

RUN cd && \
    git clone https://github.com/marselester/openface.git && \
    cd openface && \
    python setup.py install && \
    cd && \
    rm -rf openface
