FROM python:2.7-slim
MAINTAINER Marsel Mavletkulov <marselester@ya.ru>

RUN apt-get update -y && \
    apt-get install -y \
        build-essential \
        cmake \
        wget && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN pip install -q numpy==1.11.2

RUN cd && \
    wget -q https://github.com/opencv/opencv/archive/2.4.13.tar.gz && \
    tar -xf 2.4.13.tar.gz && \
    rm 2.4.13.tar.gz && \
    cd opencv-2.4.13 && \
    mkdir build && \
    cd build && \
    cmake -D CMAKE_BUILD_TYPE=RELEASE \
          -D CMAKE_INSTALL_PREFIX=/usr/local \
          -D INSTALL_C_EXAMPLES=OFF \
          -D INSTALL_PYTHON_EXAMPLES=OFF \
          -D BUILD_PYTHON_SUPPORT=ON \
          -D ENABLE_PRECOMPILED_HEADERS=OFF \
          .. && \
    make -j2 && \
    make install && \
    cd && \
    rm -rf opencv-2.4.13
