FROM marselester/opencv2-slim:latest
MAINTAINER Marsel Mavletkulov <marselester@ya.ru>

RUN apt-get update -y && \
    apt-get install -y \
        git-core \
        libboost-all-dev && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN pip install --no-cache-dir -q dlib==19.4.0

RUN cd && \
    git clone https://github.com/marselester/openface.git && \
    cd openface && \
    python setup.py install && \
    cd && \
    rm -rf openface
